name: brubaker_led_controls
description: A Brubaker home app simplified edition

publish_to: 'none'
version: 1.0.0+42

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  cached_network_image: ^3.4.0
  gal: ^2.3.1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/toadgurl.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/modes/